apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: careup-ingress
  namespace: care-up
  annotations:
    kubernetes.io/ingress.class: nginx
    
spec:
  tls:
  - hosts:
    - "server.careup.store"
    secretName: server-careup-store-tls
  rules:
  - host: server.careup.store  # 설정하려는 도메인 이름.
    http:
      paths:
      - path: /ordering-service
        pathType: Prefix
        backend:
          service:
            name: ordering-service
            port:
              number: 80
      - path: /branch-service
        pathType: Prefix
        backend:
          service:
            name: branch-service
            port:
              number: 80       