apiVersion: v1
kind: Secret
metadata:
  name: careup-secrets
  namespace: care-up
type: Opaque
data:
  # === DB 설정 ===
  DB_HOST: "database-1.cn6kck2goqrx.ap-northeast-2.rds.amazonaws.com"                  # base64 인코딩된 DB 호스트 (예: ZGF0YWJhc2UtMS5...)
  DB_PW: "1234"                    # base64 인코딩된 DB 비밀번호
  DB_USER: "admin"                  # base64 인코딩된 DB 사용자 이름

  # === AWS 설정 ===
  ACCESS_KEY: "ACCESS_KEY=AKIAXRMVYK6QAJBTNZKN"               # base64 인코딩된 AWS Access Key
  SECRET_KEY: "SECRET_KEY=2XCoVjut8CLXtkiHdXRoMd/MGlaNjRbj8N/owUAL"               # base64 인코딩된 AWS Secret Key
  S3_BUCKET: "S3_BUCKET=beyond-16-care-up"                # base64 인코딩된 S3 버킷명

  # === JWT 설정 ===
  ACCESS_TOKEN: "ACCESS_TOKEN=Q2FyZS11cC1IYW53aGEtQmV5b25kLVNXLUJhdGNoMTYtRmluYWwtUHJvamVjdC1UZWFtMi1BVC1TZWNyZXRLZXktU3VuZy1Ib28tTGlt"                     # branch-service용 Access Token Secret Key
  REFRESH_TOKEN: "REFRESH_TOKEN=Q2FyZS11cC1IYW53aGEtQmV5b25kLVNXLUJhdGNoMTYtRmluYWwtUHJvamVjdC1UZWFtMi1SVC1TZWNyZXRLZXktU3VuZy1Ib28tTGlt" 
  ACCESS_TOKEN_CUSTOMER: "ACCESS_TOKEN_CUSTOMER=Q2FyZS11cC1CZXlvbmRTVy1CYXRjaDE2LUN1c3RvbWVycy1BY2Nlc3MtVG9rZW4tU3VuZ2hvby1MaW0tMjAyNS0xMC0xMy0xMDozNw\=\="    # base64 인코딩된 고객용 Access Token Secret Key
  REFRESH_TOKEN_CUSTOMER: "REFRESH_TOKEN_CUSTOMER=Q2FyZS11cC1CZXlvbmRTVy1CYXRjaDE2LUN1c3RvbWVycy1SZWZyZXNoLVRva2VuLVN1bmdob28tTGltLTIwMjUtMTAtMTMtMTA6Mzc\="   # base64 인코딩된 고객용 Refresh Token Secret Key

  # === OPENAI 설정 ===
  OpenAi-Api-Key: "OpenAi-Api-Key=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"           # base64 인코딩된 OpenAI API Key

  # === MAIL 설정 ===
  MAIL_USER: "MAIL_USER=careup.noreply@gmail.com"                # base64 인코딩된 구글 메일 계정 (예: Y2FyZXVwQGdtYWlsLmNvbQ==)
  MAIL_PW: "MAIL_PW=shhu vhab dehe oegf"                  # base64 인코딩된 구글 앱 비밀번호

  # === OAuth 설정 ===
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID=131156890677-3cp7tqbo86ko8uk8janui2fa22sr1c1m.apps.googleusercontent.com"         # base64 인코딩된 구글 OAuth Client ID
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET=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"     # base64 인코딩된 구글 OAuth Client Secret
  KAKAO_CLIENT_ID: "KAKAO_CLIENT_ID=f2124e3fa3e4ed073b42bbc71f2bdd09"          # base64 인코딩된 카카오 REST API Key
  KAKAO_ADMIN_KEY: "KAKAO_ADMIN_KEY=9aca80aa24014004451c826d8d65e8cd"          # base64 인코딩된 카카오 Admin Key
