server:
  port: 8080

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ordering-service
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/careup
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  kafka:
    enabled: false  # Kafka 비활성화
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ordering-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.careup.ordering,com.careup.branch"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PW}
    from: careup.noreply@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  main:
    allow-bean-definition-overriding: true

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET}

payment:
  toss:
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6  # 토스 테스트 키


jwt:
  accessTokenExpiryMinutes: 30
  refreshTokenExpiryDaysPersistent: 180
  refreshTokenExpiryDaysNonPersistent: 1
  secretKeyAt: ${ACCESS_TOKEN_CUSTOMER}
  secretKeyRt: ${REFRESH_TOKEN_CUSTOMER}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:3000/oauth/google/callback
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: http://localhost:3000/oauth/kakao/callback

security:
  cors:
    allowed-origins: "http://localhost:3000"
  csrf:
    allowed-origins:
      - "http://localhost:3000"
    skip-paths:
      - "/health"

careup:
  mail:
    customer:
      reset-base-url: "http://localhost:3000/reset-password"

logging:
  level:
    root: info

